/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Main_Controller;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.Date;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ansan
 */
public class Home extends javax.swing.JFrame {
    private DefaultTableModel tableModelRegistryManagement;
    private DefaultTableModel tableModelBillsQueue;
    private DefaultTableModel tableModelInjuctionsQueue;
    private LinkedList<MouseListener> listener;

    public Home() {
        tableModelRegistryManagement = new DefaultTableModel();
        tableModelBillsQueue = new DefaultTableModel();
        tableModelInjuctionsQueue = new DefaultTableModel();
        listener = new LinkedList<>();
        //getContentPane().setLayout(new BorderLayout());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane2 = new javax.swing.JTabbedPane();
        registryManagementPanel = new javax.swing.JPanel();
        taxCLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        taxCField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        alterHolderButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        surnameLabel = new javax.swing.JLabel();
        injuctionsButton = new javax.swing.JButton();
        surnameField = new javax.swing.JTextField();
        billsButton = new javax.swing.JButton();
        contractIdLabel = new javax.swing.JLabel();
        billingAddressLabel = new javax.swing.JLabel();
        contractIdField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        billingAddressValueLabel = new javax.swing.JLabel();
        addressValueLabel = new javax.swing.JLabel();
        telephoneValueLabel = new javax.swing.JLabel();
        emailValueLabel = new javax.swing.JLabel();
        injuctionsQueuePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        confirmButtonInjuctions = new javax.swing.JButton();
        billsQueuePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reportErrorButton = new javax.swing.JButton();
        summaryBillsPanel = new javax.swing.JPanel();
        rateLabel = new javax.swing.JLabel();
        detectionLabel = new javax.swing.JLabel();
        operatorIdLabel = new javax.swing.JLabel();
        detectionDateLabel = new javax.swing.JLabel();
        dueDateLabel = new javax.swing.JLabel();
        rateValueLabel = new javax.swing.JLabel();
        detectionValueLabel = new javax.swing.JLabel();
        operatorIdValueLabel = new javax.swing.JLabel();
        detectionDateValueLabel = new javax.swing.JLabel();
        dueDateValueLabel = new javax.swing.JLabel();
        totalValueLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N

        registryManagementPanel.setLayout(new java.awt.GridBagLayout());

        taxCLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        taxCLabel.setText("Tax C./VAT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 0);
        registryManagementPanel.add(taxCLabel, gridBagConstraints);

        telephoneLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        telephoneLabel.setText("Telephone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        registryManagementPanel.add(telephoneLabel, gridBagConstraints);

        taxCField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 0, 80);
        registryManagementPanel.add(taxCField, gridBagConstraints);

        emailLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emailLabel.setText("eMail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        registryManagementPanel.add(emailLabel, gridBagConstraints);

        searchButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        searchButton.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 40);
        registryManagementPanel.add(searchButton, gridBagConstraints);

        table.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        table.setModel(tableModelRegistryManagement
        );
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 525;
        gridBagConstraints.ipady = 88;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 0, 40);
        registryManagementPanel.add(jScrollPane1, gridBagConstraints);

        addButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addButton.setText("Add");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 0);
        registryManagementPanel.add(addButton, gridBagConstraints);

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 0);
        registryManagementPanel.add(nameLabel, gridBagConstraints);

        alterHolderButton.setText("Alter holder");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 13, 0);
        registryManagementPanel.add(alterHolderButton, gridBagConstraints);

        nameField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 0, 80);
        registryManagementPanel.add(nameField, gridBagConstraints);

        removeButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        removeButton.setText("Remove");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 13, 40);
        registryManagementPanel.add(removeButton, gridBagConstraints);

        surnameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        surnameLabel.setText("Surname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 0);
        registryManagementPanel.add(surnameLabel, gridBagConstraints);

        injuctionsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        injuctionsButton.setText("Injuctions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 10, 500);
        registryManagementPanel.add(injuctionsButton, gridBagConstraints);

        surnameField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 0, 80);
        registryManagementPanel.add(surnameField, gridBagConstraints);

        billsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        billsButton.setText("Bills");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(6, 500, 10, 0);
        registryManagementPanel.add(billsButton, gridBagConstraints);

        contractIdLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        contractIdLabel.setText("Contract ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 0);
        registryManagementPanel.add(contractIdLabel, gridBagConstraints);

        billingAddressLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        billingAddressLabel.setText("Billing address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        registryManagementPanel.add(billingAddressLabel, gridBagConstraints);

        contractIdField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 40, 0, 80);
        registryManagementPanel.add(contractIdField, gridBagConstraints);

        addressLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addressLabel.setText("Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        registryManagementPanel.add(addressLabel, gridBagConstraints);

        billingAddressValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        billingAddressValueLabel.setText("       ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        registryManagementPanel.add(billingAddressValueLabel, gridBagConstraints);

        addressValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addressValueLabel.setText("      ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        registryManagementPanel.add(addressValueLabel, gridBagConstraints);

        telephoneValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        telephoneValueLabel.setText("       ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        registryManagementPanel.add(telephoneValueLabel, gridBagConstraints);

        emailValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emailValueLabel.setText("       ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        registryManagementPanel.add(emailValueLabel, gridBagConstraints);

        jTabbedPane2.addTab("Registry management", registryManagementPanel);

        injuctionsQueuePanel.setLayout(new java.awt.GridBagLayout());

        table1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        table1.setModel(tableModelInjuctionsQueue);
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 499;
        gridBagConstraints.ipady = 296;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 40);
        injuctionsQueuePanel.add(jScrollPane2, gridBagConstraints);

        deleteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteButton.setText("Delete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 20, 500);
        injuctionsQueuePanel.add(deleteButton, gridBagConstraints);

        confirmButtonInjuctions.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        confirmButtonInjuctions.setText("Confirm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 500, 20, 0);
        injuctionsQueuePanel.add(confirmButtonInjuctions, gridBagConstraints);

        jTabbedPane2.addTab("Injuctions queue", injuctionsQueuePanel);

        billsQueuePanel.setLayout(new java.awt.GridBagLayout());

        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(tableModelBillsQueue);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 588;
        gridBagConstraints.ipady = 161;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 40);
        billsQueuePanel.add(jScrollPane3, gridBagConstraints);

        reportErrorButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        reportErrorButton.setText("Report error");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 375, 20, 40);
        billsQueuePanel.add(reportErrorButton, gridBagConstraints);

        summaryBillsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Summary bills"));
        summaryBillsPanel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        rateLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rateLabel.setText("Rate (€ x m^3):");

        detectionLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        detectionLabel.setText("Detection:");

        operatorIdLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        operatorIdLabel.setText("Operator ID:");

        detectionDateLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        detectionDateLabel.setText("Detection date:");

        dueDateLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dueDateLabel.setText("Due date:");

        rateValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        detectionValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        operatorIdValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        detectionDateValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        dueDateValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        totalValueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        totalLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        totalLabel.setText("Total:");

        javax.swing.GroupLayout summaryBillsPanelLayout = new javax.swing.GroupLayout(summaryBillsPanel);
        summaryBillsPanel.setLayout(summaryBillsPanelLayout);
        summaryBillsPanelLayout.setHorizontalGroup(
            summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryBillsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rateLabel)
                    .addComponent(detectionLabel)
                    .addComponent(operatorIdLabel)
                    .addGroup(summaryBillsPanelLayout.createSequentialGroup()
                        .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detectionDateLabel)
                            .addComponent(dueDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(operatorIdValueLabel)
                            .addComponent(detectionDateValueLabel)
                            .addComponent(detectionValueLabel)
                            .addComponent(rateValueLabel)
                            .addComponent(dueDateValueLabel)
                            .addComponent(totalValueLabel)))
                    .addComponent(totalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        summaryBillsPanelLayout.setVerticalGroup(
            summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryBillsPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateLabel)
                    .addComponent(rateValueLabel))
                .addGap(6, 6, 6)
                .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detectionLabel)
                    .addComponent(detectionValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operatorIdLabel)
                    .addComponent(operatorIdValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detectionDateLabel)
                    .addComponent(detectionDateValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(summaryBillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dueDateLabel)
                    .addComponent(dueDateValueLabel)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 588;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 0, 40);
        billsQueuePanel.add(summaryBillsPanel, gridBagConstraints);

        jTabbedPane2.addTab("Bills queue", billsQueuePanel);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        for(MouseListener m: listener)
            m.mouseClicked(evt);
    }//GEN-LAST:event_jTable1MouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        for(MouseListener m: listener)
            m.mouseClicked(evt);    }//GEN-LAST:event_table1MouseClicked

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed

    }//GEN-LAST:event_tableKeyPressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        for(MouseListener m: listener)
        m.mouseClicked(evt);
    }//GEN-LAST:event_tableMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void addListener(MouseListener m){
        listener.add(m);
    }
    
    public DefaultTableModel getTableModelRegistryManagement(){
        return tableModelRegistryManagement;
    }
    
    public DefaultTableModel getTableModelBillsQueue(){
        return tableModelBillsQueue;
    }
    
    public DefaultTableModel getTableModelInjuctionsQueue(){
        return tableModelInjuctionsQueue;
    }
    
    //REGISTRY MANAGEMENT
    public void setBillingAddress(String s){
        billingAddressValueLabel.setText(s);
    }
    public void setAddress(String s){
        addressValueLabel.setText(s);
    }
    public void setTelephone(String s){
        telephoneValueLabel.setText(s);
    }
    public void setEmail(String s){
        emailValueLabel.setText(s);
    }
    public Integer getSelectedContract(){
        return table.getSelectedRow();
    }
    
    //BILL
    public Integer getSelectedBill(){
        return jTable1.getSelectedRow();
    }
    public void setTax(Float tax){
        rateValueLabel.setText(tax.toString());
    }
    public void setTotal(Float total){
        totalValueLabel.setText(total.toString());
    }
    public void setDetection(Float detection){
        detectionValueLabel.setText(detection.toString());
    }
    public void setDetector(Integer detector){
        operatorIdValueLabel.setText(detector.toString());
    }
    public void setDetectionDate(Date date){
        detectionDateValueLabel.setText(date.toString());
    }
    public void setDeadline(Date date){
        dueDateValueLabel.setText(date.toString());
    }
    
    public Integer checkTab(Component c){
        if(c == table) return 1;
        if(c == table1) return 2;
        if(c == jTable1) return 3;
        return 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressValueLabel;
    private javax.swing.JButton alterHolderButton;
    private javax.swing.JLabel billingAddressLabel;
    private javax.swing.JLabel billingAddressValueLabel;
    private javax.swing.JButton billsButton;
    private javax.swing.JPanel billsQueuePanel;
    private javax.swing.JButton confirmButtonInjuctions;
    private javax.swing.JTextField contractIdField;
    private javax.swing.JLabel contractIdLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel detectionDateLabel;
    private javax.swing.JLabel detectionDateValueLabel;
    private javax.swing.JLabel detectionLabel;
    private javax.swing.JLabel detectionValueLabel;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JLabel dueDateValueLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailValueLabel;
    private javax.swing.JButton injuctionsButton;
    private javax.swing.JPanel injuctionsQueuePanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel operatorIdLabel;
    private javax.swing.JLabel operatorIdValueLabel;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JLabel rateValueLabel;
    private javax.swing.JPanel registryManagementPanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton reportErrorButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel summaryBillsPanel;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTextField taxCField;
    private javax.swing.JLabel taxCLabel;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JLabel telephoneValueLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalValueLabel;
    // End of variables declaration//GEN-END:variables

}