/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.event.ChangeListener;
/**
 *
 * @author ansan
 */
public class Home extends javax.swing.JFrame {
    private final LinkedList<MouseListener> mouseListener;
    private final LinkedList<ActionListener> actionListener;
    private final LinkedList<ChangeListener> changeListener;
    private final LinkedList<Component> panel;
    public Home() {
        initComponents();
        
        mouseListener = new LinkedList<>();
        actionListener = new LinkedList<>();
        changeListener = new LinkedList<>();
        panel = new LinkedList<>();
        //getContentPane().setLayout(new BorderLayout());
        panel.add(new RegistryPanel());
        panel.add(new InjuctionsQueuePanel());
        panel.add(new BillsQueuePanel());
        
        homePane.addTab("Registry Management", panel.get(0));
        homePane.addTab("Injuctions Queue", panel.get(1));
        homePane.addTab("Bills Queue", panel.get(2));
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INGSW_GR12");
        setExtendedState(6);
        setName(""); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        homePane.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        homePane.setMinimumSize(new java.awt.Dimension(1121, 875));
        homePane.setPreferredSize(new java.awt.Dimension(1121, 875));
        homePane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                homePaneStateChanged(evt);
            }
        });
        getContentPane().add(homePane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");

        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jMenu2.add(help);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        for(ActionListener a: actionListener)
            a.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        for(ActionListener a: actionListener)
            a.actionPerformed(evt);
    }//GEN-LAST:event_helpActionPerformed

    private void homePaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_homePaneStateChanged
        for(ChangeListener a: changeListener)
            a.stateChanged(evt);
    }//GEN-LAST:event_homePaneStateChanged

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
            //this.setEnabled(true);
    }//GEN-LAST:event_formFocusGained
    
    @Override
    public void addMouseListener(MouseListener m){
        mouseListener.add(m);
    }
    public void addActionListener(ActionListener a){
        actionListener.add(a);
    }
    
    public void addChangeListener(ChangeListener a){
        changeListener.add(a);
    }
    
   public int checkButton(Component c){
       if(c == jMenuItem1) return 1;
       if(c == help) return 2;
       return 0;
   }
   
    public int getSelectedPanel(){
        return homePane.getSelectedIndex();
    }
    
    public Component getPanel(int i){        
        return panel.get(i);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem help;
    private javax.swing.JTabbedPane homePane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    

    

    

    

    
}