/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.LinkedList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrea
 */
public class InjuctionsQueuePanel extends javax.swing.JPanel {

    private LinkedList<MouseListener> mouseListener;
    private LinkedList<ActionListener> actionListener;
    private DefaultTableModel tableModelInjuctionsQueue;
    /**
     * Creates new form InjuctionsQueuePanel
     */
    public InjuctionsQueuePanel() {
        tableModelInjuctionsQueue = new DefaultTableModel(){
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return Integer.class;
                    case 1:
                        return Integer.class;
                    case 2:
                        return Integer.class;
                    default:
                        return Float.class;
                }
            }
            @Override
            public boolean isCellEditable(int x,int y){
                return false;
            }
        };
        mouseListener = new LinkedList<>();
        actionListener = new LinkedList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        injuctionsTable = new javax.swing.JTable();
        injuctionDeleteButton = new javax.swing.JButton();
        injuctionConfirmButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        injuctionsTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        injuctionsTable.setModel(tableModelInjuctionsQueue);
        injuctionsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                injuctionsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(injuctionsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 499;
        gridBagConstraints.ipady = 296;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 40);
        add(jScrollPane2, gridBagConstraints);

        injuctionDeleteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        injuctionDeleteButton.setText("Delete");
        injuctionDeleteButton.setEnabled(false);
        injuctionDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                injuctionDeleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 20, 0);
        add(injuctionDeleteButton, gridBagConstraints);

        injuctionConfirmButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        injuctionConfirmButton.setText("Confirm");
        injuctionConfirmButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 20, 40);
        add(injuctionConfirmButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void addMouseListener(MouseListener m){
        mouseListener.add(m);
    }
    public void addActionListener(ActionListener a){
        actionListener.add(a);
    }
    private void injuctionsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_injuctionsTableMouseClicked
        for(MouseListener m: mouseListener)
            m.mouseClicked(evt);
    }//GEN-LAST:event_injuctionsTableMouseClicked

    private void injuctionDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_injuctionDeleteButtonActionPerformed
        for(ActionListener a: actionListener)
            a.actionPerformed(evt);
    }//GEN-LAST:event_injuctionDeleteButtonActionPerformed

public void activeInjuctionButtons(){
        injuctionConfirmButton.setEnabled(true);
        injuctionDeleteButton.setEnabled(true);
    }
      public JTable getInjuctionTable() {
        return injuctionsTable;
    }
    public Integer getSelectedInjuction() {
        return injuctionsTable.getSelectedRow();
    }
    
        public DefaultTableModel getTableModelInjuctionsQueue(){
        return tableModelInjuctionsQueue;
    }
    
                public int checkButton(Component c){
            if(c == injuctionConfirmButton)  return 1;
            if(c == injuctionDeleteButton) return 2;
            return 0;
        }
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton injuctionConfirmButton;
    private javax.swing.JButton injuctionDeleteButton;
    private javax.swing.JTable injuctionsTable;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
